### PR TITLE
GML-1223: Add model with non-graph features

### PR DESCRIPTION
**Pull request by billshitg**

### CODE REVIEW

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SKIPPED, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/660/

**Comment by parkererickson-tg** [comment]
LGTM as long as e2e tests pass.

**Review by parkererickson-tg — APPROVED** [review]

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SKIPPED, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/662/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SKIPPED, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/663/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SKIPPED, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/664/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
