### PR TITLE
GML-373: NodePiece Example Notebooks

### PR DESCRIPTION
**Pull request by parkererickson-tg**
Rough drafts for now. Need to add more descriptions, clean up a bit.

### CODE REVIEW

**Comment by parkererickson-tg** [comment]
Docs updated.

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SKIPPED, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/576/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Review by billshitg — APPROVED** [review]
One suggestion: could you add a statement at the beginning about pyTG version compatibility? like "nodepieceloader is only available in pyTigerGraph 1.x and above" or something alone those lines. Would be nice to start doing this for new features in the future.

And one minor thing: the embedding visualization looks like no pattern is there. It is what it is, and no change is needed. Just wondering if I read it correct.

**Comment by parkererickson-tg** [comment]
Yeah, unfortunately there isn't a real pattern. I will add the compatibility statement.

**Comment by parkererickson-tg** [comment]
Updated.

**Comment by billshitg** [comment]
Thanks! Feel free to ship it when you think it is ready.

**Comment by parkererickson-tg** [comment]
We need to release pyTG v1.3 first.

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SUCCESS, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/582/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Pull request merged**
