### PR TITLE
feat(ethereum notebook): add built-in model

### PR DESCRIPTION
**Pull request by parkererickson-tg**

### CODE REVIEW

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SKIPPED, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/799/

**Review by qe-tigergraph — CHANGES_REQUESTED** [review]
Unit Test: SKIPPED, e2e Test: FAILURE, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/800/

**Review by qe-tigergraph — COMMENTED** [review]
Unit Test: SKIPPED, e2e Test: SUCCESS, Jenkins_job:http://192.168.99.101:30080/job/mlwb_build/801/

**Review by qe-tigergraph — APPROVED** [review]
QE Approved

**Comment by billshitg** [comment]
Any idea on why the recall of GNN dropped significantly?

**Pull request merged**
